![image](figs/fig-numpy.png)
# Introducción a NumPy (...Continuación)



### - NumPy es una de las bibliotecas fundamentales en el ecosistema de Python para la ciencia de datos y la computación numérica. 

### - Proporciona soporte para arreglos multidimensionales y funciones matemáticas avanzadas.
### - La convierte en una herramienta esencial para el análisis de datos

### [https://numpy.org](https://numpy.org)


## ¿Qué es NumPy?

### NumPy (Numerical Python) es una biblioteca de Python que ofrece:

###  - **Arreglos multidimensionales:** Estructuras de datos eficientes para almacenar y manipular grandes conjuntos de datos numéricos.

### - **Funciones matemáticas avanzadas:** Operaciones matemáticas y estadísticas que funcionan de manera eficiente en arreglos completos.

### - **Operaciones vectorizadas:** Cálculos rápidos sin necesidad de bucles explícitos, gracias a la implementación en C.


# Contenido del Tutorial

###  1. **Instalación de NumPy**
  #### - Cómo instalar NumPy usando `pip` o `conda`.

### 2. **Conceptos Básicos de Arreglos**
   #### - Creación de arreglos con `np.array()`.
   #### - Indexación y segmentación de arreglos.
   #### - Tipos de datos y conversiones entre tipos.

### 3. **Operaciones Matemáticas y Estadísticas**
   #### - Operaciones aritméticas básicas: suma, resta, multiplicación y división.
   #### - Funciones estadísticas: media, mediana, desviación estándar.

### 4. **Manipulación de Arreglos**
   #### - Cambio de forma con `reshape()`.
   #### - Transposición y otras operaciones de reordenamiento.
   #### - Combinación y división de arreglos.

### 5. **Operaciones Avanzadas**
   #### - Uso de funciones de álgebra lineal: productos matriciales, determinantes y valores singulares.

In [1]:
import numpy as np

# Ejes de Numpy (AXIS)

- ### Los ejes de NumPy son muy similares a los ejes de un sistema de coordenadas cartesianas.
- ### Axis = 0 indica el primer eje. Suponiendo que estamos hablando de matrices multidimensionales, el eje 0 es el eje que de las filas (se aplica a 2d y arrays multidimensionales).
- ### Axis = 1 indica el segundo eje. Este es el eje horizontal que cruza las columnas
- ### Para entender cómo utilizar el parámetro de eje en las funciones de NumPy, es  importante comprender qué controla realmente el parámetro de eje para cada función.

![image](./figs/fig-np-axis0-1.png)

## Función $sum$  de NUMPY con AXIS = 0
- ### La función $sum$ suma a través  de las columnas. El resultado es un nuevo array que contiene la suma de cada columna.
- ### En np.sum(), el parámetro de eje (axis) controla qué eje se agregará. Es decir, el parámetro axis controla qué eje se contraerá.

- ### Funciones como sum(), mean(), min(), median() y otras funciones estadísticas agregan sus datos.

- ### Cuando establecemos axis = 0, la función suma las columnas. El resultado es una nueva matriz de NumPy que contiene la suma de cada columna.

- ### En la figura, se colapsan los renglones (axis=0) y calcula la suma de cada columna.


![image](./figs/fig-np-axis0.png)

In [1]:
#A = np.arange(0, 6).reshape([2,3])
import numpy as np
A = np.array([[0, 1, 2],
              [3, 4, 5]
              ])

print(f"A=\n{A}\n")

print(np.sum(A, axis=0))

A=
[[0 1 2]
 [3 4 5]]

[3 5 7]


In [ ]:
#Suma las columnas pero mantiene las dimensiones originales con keepdims
print(np.sum(A, axis=0, keepdims=True))

## SUM de NUMPY con AXIS = 1

- ### La función $sum$ suma a través  de los renglones. El resultado es un nuevo array que contiene la suma de cada columna.

- ### Cuando establecemos axis = 1, la función suma los renglones. El resultado es una nueva matriz de NumPy que contiene la suma de cada renglon.

- ### En la figura, se colapsan las columnas  (axis=1) y se calcula la suma de cada renglon.


![image](./figs/fig-np-axis1.png)

In [ ]:
# A = np.arange(0, 6).reshape([2,3])

A = np.array([[0, 1, 2],
              [3, 4, 5]
              ])

print(f"A=\n{A}\n")
print(np.sum(A, axis=1))


In [ ]:

B= np.sum(A, axis=1)
print(f"B=\n{B}\n")
B.shape

## Suma las columnas pero mantiene las dimensiones originales con $keepdims$


In [ ]:
# Suma las columnas pero mantiene las dimensiones originales con keepdims

print(f"A=\n{A}\n")
print(np.sum(A, axis=1, keepdims=True))

In [ ]:
B= np.sum(A, axis=1, keepdims=True)
print(f"B=\n{B}\n")
B.shape

## SUM de NUMPY sin  AXIS 

- ### Suma de manera global

In [ ]:
A = np.array([[0, 1, 2],
              [3, 4, 5]
              ])

print(f"A=\n{A}\n")
print(np.sum(A))

# Ejercicios:



## Dada la siguiente: matriz score_matrix Realizar las operaciones que se indican

```Python
import numpy as np

# Cada fila representa a un estudiante
# y cada columna representa una materia  diferente con sus puntuaciones
scores_matrix = np.array([
    [85, 78, 92, 88, 76],  # Puntuaciones del estudiante 1
    [90, 85, 89, 92, 84],  # Puntuaciones del estudiante 2
    [70, 65, 80, 75, 72],  # Puntuaciones del estudiante 3
    [88, 90, 85, 91, 87],  # Puntuaciones del estudiante 4
    [76, 80, 78, 74, 73],  # Puntuaciones del estudiante 5
    [95, 92, 90, 94, 91]   # Puntuaciones del estudiante 6
])
```


# Operaciones
- ### 1. Obtener la media de calificaciones por estudiante 

- ### 2. Obtener la desviación estándar de las calificaciones  por  cada estudiante

- ### 3. Obtener la calificación máxima por estudiante

- ### 4. Obtener la Puntuación Máxima y Mínima por materia

- ### 5. Obtener la desviación estándar de las calificaciones para cada materia

- ### 6. Media de las Puntuaciones por cada materia

In [4]:
import numpy as np

scores_matrix = np.array([
    [85, 78, 92, 88, 76],  # Puntuaciones del estudiante 1
    [90, 85, 89, 92, 84],  # Puntuaciones del estudiante 2
    [70, 65, 80, 75, 72],  # Puntuaciones del estudiante 3
    [88, 90, 85, 91, 87],  # Puntuaciones del estudiante 4
    [76, 80, 78, 74, 73],  # Puntuaciones del estudiante 5
    [95, 92, 90, 94, 91]   # Puntuaciones del estudiante 6
])

media_estudiante = np.mean(scores_matrix, axis=1, keepdims=True)
desviacion_estandar_estudiante = np.std(scores_matrix, axis=1, keepdims=True)
maximo_estdiante = np.max(scores_matrix, axis=1, keepdims=True)
maximo_materia = np.max(scores_matrix, axis=0, keepdims=True)
minimo_materia = np.min(scores_matrix, axis=0, keepdims=True)
desviacion_estandar_materia = np.std(scores_matrix, axis=0, keepdims=True)
media_materia = np.mean(scores_matrix, axis=0, keepdims=True)

print(f'Datos por estudiante\nMedia:\n{media_estudiante}\nDesviación estándar:\n{desviacion_estandar_estudiante}\nCalificación máxima:\n{maximo_estdiante}')
print(f'\nDatos por materia\nMedia: {media_materia}\tDesviación estándar: {desviacion_estandar_materia}\nCalificación máxima: {maximo_materia}\tCalificación mínima: {minimo_materia}')


Datos por estudiante
Media:
[[83.8]
 [88. ]
 [72.4]
 [88.2]
 [76.2]
 [92.4]]
Desviación estándar:
[[6.01331855]
 [3.03315018]
 [5.0039984 ]
 [2.13541565]
 [2.56124969]
 [1.8547237 ]]
Calificación máxima:
[[92]
 [92]
 [80]
 [91]
 [80]
 [95]]

Datos por materia
Media: [[84.         81.66666667 85.66666667 85.66666667 80.5       ]]	Desviación estándar: [[8.50490055 8.9566859  5.18544973 8.09663853 7.22841615]]
Calificación máxima: [[95 92 92 94 91]]	Calificación mínima: [[70 65 78 74 72]]


# Concatenación de matrices

## $Concatenate$ de NUMPY con AXIS = 0
- ### Cuando usamos el parámetro axis con la función np.concatenate(), el parámetro axis define el eje a lo largo del cual se apilan las matrices.
- ### Cuando establecemos axis = 0, le estamos indicando a la función concatenar que apile las dos matrices a lo largo de las filas. 
- ### Estamos especificando que queremos concatenar las matrices a lo largo del eje 0.

![image](./figs/fig-np-concatenate-axis0.png)


In [ ]:
A= np.array([[1, 1, 1],
             [1, 1, 1]])

B = np.array([[9, 9, 9],
              [9, 9, 9]])

print(f'A=\n{A}\n')
print(f'B=\n{B}\n')

np.concatenate([A, B], axis = 0)

## $Concatenate$ de NUMPY con AXIS = 1
- ### Cuando usamos el parámetro axis con la función np.concatenate(), el parámetro axis define el eje a lo largo del cual se apilan las matrices.
- ### Cuando establecemos axis = 1, le estamos indicando a la función concatenar que apile las dos matrices de manera horizontal, a lo largo de las columnas. 
- ### Estamos especificando que queremos concatenar las matrices a lo largo del eje 1.

![image](./figs/fig-np-concatenate-axis1.png)


In [ ]:
A= np.array([[1, 1, 1],
             [1, 1, 1]])

B = np.array([[9, 9, 9],
              [9, 9, 9]])

print(f'A=\n{A}\n')
print(f'B=\n{B}\n')

np.concatenate((A, B), axis = 1)

## Arrays de 1-DIMENSIONAL

- ### Estos arreglos solo tiene un eje (axis=0)
- ### En este caso, la función funciona correctamente. NumPy concatena estas matrices (1-d) a lo largo del eje 0. 
- ### El problema es que en las matrices unidimensionales, el eje 0 no apunta "hacia abajo" como lo hace en una matriz bidimensional.

In [ ]:
a = np.array([1,1,1])
b = np.array([9,9,9])

print(f'a=\n{a}\n')
print(f'b=\n{b}\n')


np.hstack((a, b))

## $hstack$

- ### Apila matrices en secuencia horizontalmente (columna por columna).

- ### Esto es equivalente a la concatenación a lo largo del segundo eje, excepto para matrices 1-D donde se concatena a lo largo del primer eje.
- ### Reconstruye matrices divididas por $hsplit$.

In [ ]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6, 7],
              [8, 9, 10]])
print(f'a=\n{a}\n')
print(f'b=\n{b}\n')

print("hstack\n", np.hstack((a, b)))

# Vectores columna
$$
\mathbf{a} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}, \quad
\mathbf{b} = \begin{bmatrix} 4 \\ 5 \\ 6 \end{bmatrix}
\quad

\mathbf{c} = \mathbf{[a|b]= }  \begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6 \\
\end{bmatrix}

$$

In [ ]:
import numpy as np

# Vectores columna
a = np.array([[1],
              [2],
              [3]])

b = np.array([[4],
              [5],
              [6]])

print(f'a=\n{a}\n')
print(f'b=\n{b}\n')

c = np.hstack((a,b))
print(f'c=\n{c}\n')
print(c.shape)

## $vstack$

- ### Apila matrices en secuencia verticalmente (fila por fila).

- ### Esto es equivalente a la concatenación a lo largo del primer eje después de que las matrices 1-D de forma (N,) hayan sido reformadas a (1,N). 

- ### Reconstruye matrices divididas por vsplit.

In [ ]:

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [8, 9],
              [10, 11]])

print(f'a= \n{a}\n')
print(f'b= \n{b}\n')
print("\nvstack\n", np.vstack((a, b)))

## $vsplit$ 
- ### Dividir una matriz en múltiples submatrices verticalmente (fila por fila)

In [ ]:
import numpy as np
x = np.arange(24).reshape(6, 4)
print(f'x= \n{x}\n')
np.vsplit(x, 2)

## $hsplit$ 
- ### Dividir una matriz en múltiples submatrices horizontalmente (columna por columna)

In [ ]:
import numpy as np
x = np.arange(24).reshape(6, 4)
print(f'x= \n{x}\n')
np.hsplit(x, 2)

## Operaciones con matrices
 - ### suma, resta

In [ ]:
# Crear matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matriz A:")
print(A)

print("\nMatriz B:")
print(B)

# Suma y resta de matrices
suma = A + B
resta = A - B

print("\nSuma de matrices:")
print(suma)

print("\nResta de matrices:")
print(resta)

## Producto Hadamard
### El producto Hadamard $ C $ se expresa como:
$ C = A \odot B $  

### o 

$ C = A * B $

### donde cada elemento $ c_{ij} $ de la matriz $ C $ se calcula como:

### $ c_{ij} = a_{ij} \odot b_{ij} $

## donde $ a_{ij} $ y $ b_{ij} $ son los elementos correspondientes de las matrices $ A $ y $ B $, respectivamente.

In [12]:
# Crear matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matriz A:")
print(A)

print("\nMatriz B:")
print(B)

# Multiplicación de matrices (Elemento a elemento )
multiplicacion_elemental = A * B  # Multiplicación elemento a elemento

print("\nMultiplicación elemento a elemento de matrices:")
print(multiplicacion_elemental)

# Multiplicación de matrices (Elemento a elemento )
multiplicacion_elemental2 = np.multiply(A, B) # Multiplicación elemento a elemento

print("\nMultiplicación elemento a elemento de matrices:")
print(multiplicacion_elemental2)

Matriz A:
[[1 2]
 [3 4]]

Matriz B:
[[5 6]
 [7 8]]

Multiplicación elemento a elemento de matrices:
[[ 5 12]
 [21 32]]

Multiplicación elemento a elemento de matrices:
[[ 5 12]
 [21 32]]


In [13]:

multiplicacion_matricial = np.dot(A, B)  # Multiplicación matricial 1 (caso especial para 1-D matriz, se realiza el producto escalar)

multiplicacion_matricial2 = np.matmul(A, B)  # Multiplicación matricial 2

multiplicacion_matricial3 = A @ B  # Multiplicación matricial 3


# El resultado es el mismo con 3 formas de realizarlo 

print("\nMultiplicación matricial:")
print(multiplicacion_matricial)

print("\nMultiplicación matricial (matmul):")
print(multiplicacion_matricial2)

print("\nMultiplicación matricial (@):")
print(multiplicacion_matricial2)


Multiplicación matricial:
[[19 22]
 [43 50]]

Multiplicación matricial (matmul):
[[19 22]
 [43 50]]

Multiplicación matricial (@):
[[19 22]
 [43 50]]


## Operaciones sobre matrices
 - ### Transpuesta
 - ### Inversa: La inversa de A (debe ser cuadrada) se denota $ A^{-1} $  cumple que $A \cdot A^{-1} = I$ ; el determinante es no nulo
 - ### Determinante

In [ ]:
# Transposición
transpuesta_A = np.transpose(A)
transpuesta_B = np.transpose(B)

print("A=\n", A)
print("\nTransposición de la matriz A:")
print(transpuesta_A)

print("\nTransposición de la matriz A con operador T:")
print(A.T)

print("\nB=\n", B)
print("\nTransposición de la matriz B:")
print(transpuesta_B)

print("\nTransposición de la matriz B con operador T:")
print(B.T)

A=
 [[1 2]
 [3 4]]

Transposición de la matriz A:
[[1 3]
 [2 4]]

Transposición de la matriz A con operador T:
[[1 3]
 [2 4]]

B=
 [[5 6]
 [7 8]]

Transposición de la matriz B:
[[5 7]
 [6 8]]

Transposición de la matriz B con operador T:
[[5 7]
 [6 8]]


In [8]:
# Determinante

A = np.array([[1, 2], 
              [3, 4]])

B = np.array([[5, 6], 
              [7, 8]])


determinante_A = np.linalg.det(A)
determinante_B = np.linalg.det(B)

print("\nDeterminante de la matriz A:")
print(determinante_A)

print("\nDeterminante de la matriz B:")
print(determinante_B)

np.linalg.inv(A)


Determinante de la matriz A:
-2.0000000000000004

Determinante de la matriz B:
-1.999999999999999


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
# Matriz Inversa
A = np.array([[0, -1], 
              [2, 0]])
              

print("Matriz A= ")
print(A)              
inversa_A = np.linalg.inv(A)

inversa_B = np.linalg.inv(B)

print("\nInversa de la matriz A:")
print(inversa_A)

print("\nMultiplicacion de la matriz A @ A(-1):")

print(A @ inversa_A)

print("\nInversa de la matriz B:")
print(inversa_B)

print(f'\nA * A^-1:\n{A @ inversa_A}')

Matriz A= 
[[ 0 -1]
 [ 2  0]]

Inversa de la matriz A:
[[ 0.   0.5]
 [-1.  -0. ]]

Multiplicacion de la matriz A @ A(-1):
[[1. 0.]
 [0. 1.]]

Inversa de la matriz B:
[[-4.   3. ]
 [ 3.5 -2.5]]

A * A^1:
[[1. 0.]
 [0. 1.]]


In [ ]:
#Matriz no invertible

A = np.array([[2, 4],
              [1, 2]])
print("\nInversa de la matriz A:")
print(A)              

try: 
    print("determinante de A = ", np.linalg.det(A))
    inversa_A = np.linalg.inv(A)
    print(inversa_A)
except np.linalg.LinAlgError as err:
    print("error:", err)
    print("la matriz no es invertible")

## Filtrado de datos de un arreglo

In [ ]:
# Generar matriz aleatoria
matriz = np.random.randint(1, 10, (4, 4))

# Filtrar elementos mayores a 5
elementos_filtrados = matriz[matriz > 5] #Filtrado de datos

print("Matriz original:")
print(matriz)
print("\nElementos mayores a 5:")
print(elementos_filtrados)

## Ejercicios

### 1. **Transponer e Invertir**:
   - ### Crea una matriz $ 3 \times 3 $, transponerla  y calcula su inversa (si es posible).
   - ### Verifica si la matriz Identidad es igual al producto de la matriz y su inversa.


### 2. **Producto de Hadamard y Determinante**:
   - ### Crea dos matrices $ 3 \times 3 $ y calcula el producto de Hadamard.
   - ### Calcula el determinante de una matriz $ 4 \times 4 $ 

### 3. **Filtrado de datos**:
   - ### Genera una matriz 4x4 de números aleatorios entre 1 y 20. Filtra las filas cuya suma de elementos es mayor a 30.


In [25]:
matriz3x3 = np.array([[1,1,3], [4,5,6], [7,8,9]])
matriz_transpuesta = np.transpose(matriz3x3)
matriz_inversa = np.linalg.inv(matriz_transpuesta)
print(f'A =\n{matriz3x3}\nA^T =\n{matriz_transpuesta}\n(A^T)^-1 = \n{matriz_inversa}\n\n((A^T)^-1)(A^T) =\n{matriz_transpuesta@matriz_inversa}')


A =
[[1 1 3]
 [4 5 6]
 [7 8 9]]
A^T =
[[1 4 7]
 [1 5 8]
 [3 6 9]]
(A^T)^-1 = 
[[ 0.5        -1.          0.5       ]
 [-2.5         2.          0.16666667]
 [ 1.5        -1.         -0.16666667]]

((A^T)^-1)(A^T) =
[[1.00000000e+00 8.88178420e-16 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]


In [36]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
B = np.array([[2,2,2], [2,2,2], [2,2,2]])
print(f'A =\n{A}\nB =\n{B}\nA*B =\n{A*B}\n')

C = np.array([[2, 3, 1, 5], [4, 1, 3, 2], [1, 2, 0, 3], [3, 0, 2, 4]])
print(f'C =\n{C}\n|C| = {np.linalg.det(C)}')

A =
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B =
[[2 2 2]
 [2 2 2]
 [2 2 2]]
A*B =
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

C =
[[2 3 1 5]
 [4 1 3 2]
 [1 2 0 3]
 [3 0 2 4]]
|C| = 16.000000000000007


In [54]:
matriz4x4 = np.random.randint(1, 21, (4,4))
sumas = np.sum(matriz4x4, axis=1, keepdims=True)
filas = [i for i in range(len(sumas)) if sumas[i] > 30]
print(f'Matriz:\n{matriz4x4}\nSumatoria por fila:\n{sumas}\nFilas mayores a 30:\n{filas}')

Matriz:
[[ 5 12 14 16]
 [ 9 13 19 13]
 [ 5 10 14  1]
 [10  2 14 12]]
Sumatoria por fila:
[[47]
 [54]
 [30]
 [38]]
Filas mayores a 30:
[0, 1, 3]


## Ejercicio: Análisis de Temperaturas

### **Descripción**
#### Una estación meteorológica registra las temperaturas (en grados Celsius) en una ciudad durante una semana a tres diferentes horas del día: **mañana (8 AM), tarde (2 PM) y noche (8 PM)**. Los datos se almacenan en una matriz de NumPy de la siguiente forma:

```
T =
[[15, 22, 18],
 [14, 24, 17],
 [16, 23, 19],
 [15, 25, 20],
 [17, 26, 21],
 [18, 27, 22],
 [19, 28, 23]]
```

#### Donde:
- #### **Filas**: representan los días de la semana (de lunes a domingo).
- #### **Columnas**: representan las horas del día (mañana, tarde, noche).

### **Instrucciones**
####  1. **Crear la matriz** `T` en NumPy con los datos proporcionados.
#### 2. **Obtener la temperatura promedio** de cada día.
#### 3. **Obtener la temperatura promedio** de cada horario (mañana, tarde y noche).
#### 4. **Determinar el día más frío** (día con menor temperatura promedio).
#### 5. **Determinar el día más caluroso** (día con mayor temperatura promedio).
#### 6. **Determinar la temperatura máxima y mínima** de toda la semana.

In [ ]:
T = np.array([
    [15, 22, 18],
    [14, 24, 17],
    [16, 23, 19],
    [15, 25, 20],
    [17, 26, 21],
    [18, 27, 22],
    [19, 28, 23]
])

dias = [['Lunes'],
        ['Martes'],
        ['Miércoles'], 
        ['Jueves'],
        ['Viernes'],
        ['Sábado'],
        ['Domingo']]

horarios = ['Mañana', 'Tarde', 'Noche']

t_promedio_dia = np.average(T, axis=1, keepdims=True)
t_promedio_horario = np.average(T, axis=0)
dia_frio = np.argmin(t_promedio_dia)
dia_caliente = np.argmax(t_promedio_dia)
t_minima = np.min(T)
t_maxima = np.max(T)

print(f'Temperatura promedio por día:\n{np.concatenate([dias, t_promedio_dia], axis=1)}', end='\n\n')
print(f'Temperatura promedio por horario:\n{horarios}\n{t_promedio_horario}', end='\n\n')
print(f'Día más frío: {dias[dia_frio][0]} con {t_promedio_dia[dia_frio][0]}°C', end='\n\n')
print(f'Día más caliente: {dias[dia_caliente][0]} con {t_promedio_dia[dia_caliente][0]}°C', end='\n\n')
print(f'Temperatura más fría de la semana:{t_minima}\tTemperatura más caliente de la semana:{t_maxima}', end='\n\n')


Temperatura promedio por día:
[['Lunes' '18.333333333333332']
 ['Martes' '18.333333333333332']
 ['Miércoles' '19.333333333333332']
 ['Jueves' '20.0']
 ['Viernes' '21.333333333333332']
 ['Sábado' '22.333333333333332']
 ['Domingo' '23.333333333333332']]

Temperatura promedio por horario:
['Mañana', 'Tarde', 'Noche']
[16.28571429 25.         20.        ]

Día más frío:
Lunes con 18.333333333333332°

Día más caliente:
Domingo con 23.333333333333332°

