![image](figs/fig-numpy.png)
# Introducción a NumPy (...Continuación)



### - NumPy es una de las bibliotecas fundamentales en el ecosistema de Python para la ciencia de datos y la computación numérica. 

### - Proporciona soporte para arreglos multidimensionales y funciones matemáticas avanzadas.
### - La convierte en una herramienta esencial para el análisis de datos

### [https://numpy.org](https://numpy.org)


## ¿Qué es NumPy?

### NumPy (Numerical Python) es una biblioteca de Python que ofrece:

###  - **Arreglos multidimensionales:** Estructuras de datos eficientes para almacenar y manipular grandes conjuntos de datos numéricos.

### - **Funciones matemáticas avanzadas:** Operaciones matemáticas y estadísticas que funcionan de manera eficiente en arreglos completos.

### - **Operaciones vectorizadas:** Cálculos rápidos sin necesidad de bucles explícitos, gracias a la implementación en C.


# Contenido del Tutorial

###  1. **Instalación de NumPy**
  #### - Cómo instalar NumPy usando `pip` o `conda`.

### 2. **Conceptos Básicos de Arreglos**
   #### - Creación de arreglos con `np.array()`.
   #### - Indexación y segmentación de arreglos.
   #### - Tipos de datos y conversiones entre tipos.

### 3. **Operaciones Matemáticas y Estadísticas**
   #### - Operaciones aritméticas básicas: suma, resta, multiplicación y división.
   #### - Funciones estadísticas: media, mediana, desviación estándar.

### 4. **Manipulación de Arreglos**
   #### - Cambio de forma con `reshape()`.
   #### - Transposición y otras operaciones de reordenamiento.
   #### - Combinación y división de arreglos.

### 5. **Operaciones Avanzadas**
   #### - Uso de funciones de álgebra lineal: productos matriciales, determinantes y valores singulares.


In [1]:
import numpy as np

# Broadcasting 
- ### El término broadcasting describe cómo NumPy trata las matrices con diferentes formas durante las operaciones aritméticas. 
- ### Sujeto a ciertas restricciones, la matriz más pequeña se "transmite" a través de la matriz más grande para que tengan formas compatibles.

- ### Las operaciones de NumPy se realizan normalmente en pares de matrices, elemento por elemento. En el caso más simple, las dos matrices deben tener exactamente la misma forma.

- ### Al operar sobre dos matrices, NumPy compara sus formas elemento por elemento. Comienza con la dimensión final (es decir, la más a la derecha) y avanza hacia la izquierda. 
    - ### <span style="color:red;">Dos dimensiones son compatibles cuando: son iguales o una de ellas es de dimensión 1.</span> 

- ### Las matrices de entrada no necesitan tener la misma cantidad de dimensiones. 
- ### <span style="color:red;">La matriz resultante tendrá la misma cantidad de dimensiones que la matriz de entrada con la mayor cantidad de dimensiones</span>, donde el tamaño de cada dimensión es el tamaño más grande de la dimensión correspondiente entre las matrices de entrada. 
- ### Considere que se supone que las dimensiones faltantes tienen un tamaño de uno.


- ### En numpy, la instrucción A * B calcula la multiplicación elemento por elemento de las matrices o tensores A y B. 
    - ### <span style="color:red;">Si las matrices tienen formas diferentes, se convertirán automáticamente para que tengan formas compatibles</span> __replicando implícitamente ciertas dimensiones__; esto <span style="color:red;"> se denomina broadcasting</span> . Las siguientes reglas de conversión se aplican en orden:

        - #### 1. Si las dos matrices difieren en su número de dimensiones, la forma de la matriz que tiene menos dimensiones se rellena con dimensiones 1 en el lado izquierdo. Por ejemplo, un escalar se convertirá en un vector shape=(1,) y un vector en una matriz con una fila shape=(1,N).
        - #### 2. Si la forma de las dos matrices no coincide en ninguna dimensión, la matriz con forma igual a 1 en esa dimensión se estira para que coincida con la otra forma, replicando el contenido correspondiente.
        - #### 3. Si en alguna dimensión los tamaños no coinciden y ninguno es igual a 1, se genera un error.


## Ejemplo 1
![image](./figs/fig-broadcasting1.png)

- Una matriz unidimensional (b) agregada a una matriz bidimensional (a) da como resultado un "broadcasting" si el número de elementos de la matriz unidimensional coincide con el número de columnas de la matriz bidimensional.

In [ ]:
import numpy as np

a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])

b = np.array([1.0, 2.0, 3.0])

print(f'a=\n{a}\n')
print(f'a.shape=\n{a.shape}\n')

print(f'b=\n{b}\n')
print(f'b.shape=\n{b.shape}\n')

print(f'a+b=\n{a+b}\n')

a=
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]

a.shape=
(4, 3)

b=
[1. 2. 3.]

b.shape=
(3,)

a+b=
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]



## Ejemplo 2
![image](./figs/fig-broadcasting2.png)


In [ ]:
import numpy as np

a = np.array([[ 0.],
              [10.],
              [20.],
              [30.]])

b = np.array([1.0, 2.0, 3.0])

print(f'a=\n{a}\n')
print(f'a.shape=\n{a.shape}\n')

print(f'b=\n{b}\n')
print(f'b.shape=\n{b.shape}\n')

print(f'a+b=\n{a+b}\n')

# Expandir dimensiones
- ## $np.expand\_dims$: Inserta un nuevo eje que aparecerá en la posición del eje en la forma de la matriz expandida.
- ## Útil para hacer broadcasting

## Vector fila, se agrega mediante axis=0

In [ ]:
a = np.array([1, 2, 3])

print(f'a=\n{a}\n')
print(f'a.shape=\n{a.shape}\n')

# agregar dimensión al vector a, lo convierte en vector fila
b = np.expand_dims(a, axis=0)

print(f'b=\n{b}\n')
print(f'b.shape=\n{b.shape}\n')

a=
[1 2 3]

a.shape=
(3,)

b=
[[1 2 3]]

b.shape=
(1, 3)



### Forma equivalente con $np.newaxis$ equivalente a agregar $None$ en el eje de las filas

In [ ]:

# teniendo "a" como vector se puede agregar una dimensión adicional con np.newaxis es equivalente a gregar None 

a = np.array([0, 10, 20, 30])

print(f'a=\n{a}\n')

b = a[np.newaxis, :] # agrega una dimension en el eje de las filas

print(f'b=\n{b}\n')
print(f'b.shape=\n{b.shape}\n')

c = a[None, :] # agrega una dimension en el eje de las filas

print(f'c=\n{c}\n')
print(f'c.shape=\n{c.shape}\n')

## Vector columna, se agrega mediante axis=1

In [ ]:
a = np.array([1, 2, 3])

print(f'a=\n{a}\n')
print(f'a.shape=\n{a.shape}\n')

# # agregar dimensión al vector a, lo convierte en vector columna 
b = np.expand_dims(a, axis=1)

print(f'b=\n{b}\n')
print(f'b.shape=\n{b.shape}\n')

### Forma equivalente con $np.newaxis$ equivalente a agregar $None$ en el eje de las columnas

In [ ]:

# teniendo "a" como vector se puede agregar una dimensión adicional con np.newaxis es equivalente a gregar None 

a = np.array([0, 10, 20, 30])

print(f'a=\n{a}\n')

b = a[:, np.newaxis] # agrega una dimension en el eje de las columnas

print(f'b=\n{b}\n')
print(f'b.shape=\n{b.shape}\n')

c = a[:, None] # agrega una dimension en el eje de las columnas

print(f'c=\n{c}\n')
print(f'c.shape=\n{c.shape}\n')

### Formas equivalentes reshape: comodín -1  (ajusta los elementos para completar la forma adecuada, usar solo una dimensión no conocida) 

In [ ]:
# teniendo "a" como vector se puede agregar una dimensión adicional con np.newaxis es equivalente a usar reshape

a = np.array([0, 10, 20, 30])

print(f'a=\n{a}\n')

b = a[np.newaxis, :] # agrega una dimension en el eje de las filas

print(f'b=\n{b}\n')
print(f'b.shape=\n{b.shape}\n')

c = a.reshape(-1, 4) # agrega una dimension en el eje de las filas

print(f'c=\n{c}\n')
print(f'c.shape=\n{c.shape}\n')

In [ ]:
# teniendo "a" como vector se puede agregar una dimensión adicional con np.newaxis es equivalente a usar reshape

a = np.array([0, 10, 20, 30])

print(f'a=\n{a}\n')

b = a[:, np.newaxis] # agrega una dimension en el eje de las columnas

print(f'b=\n{b}\n')
print(f'b.shape=\n{b.shape}\n')

c = a.reshape(4, -1) # agrega una dimension en el eje de las filas

print(f'c=\n{c}\n')
print(f'c.shape=\n{c.shape}\n')

In [ ]:
a = np.array([[1, 2],
              [3, 4]])


b = np.array([[5, 6, 7],
              [8, 9, 10]])

c = a[np.newaxis,:].reshape()
c+b

# $np.squeeze$ Remover ejes (dimesión) de longitud 1 de la matriz.

In [ ]:
a = np.array([[[0], [1], [2]]])

print(f"a=\n{a}\n")
print(f"a.shape=\n{a.shape}\n")

b = np.squeeze(a)

print(f"b=\n{b}\n")
print(f"b.shape=\n{b.shape}\n")

a=
[[[0]
  [1]
  [2]]]

a.shape=
(1, 3, 1)

b=
[0 1 2]

b.shape=
(3,)



In [ ]:
# Eliminar eje 0
a = np.array([[[0], [1], [2]]])

print(f"a=\n{a}\n")
print(f"a.shape=\n{a.shape}\n")

b = np.squeeze(a, axis=0)

print(f"b=\n{b}\n")
print(f"b.shape=\n{b.shape}\n")

a=
[[[0]
  [1]
  [2]]]

a.shape=
(1, 3, 1)

b=
[[0]
 [1]
 [2]]

b.shape=
(3, 1)



In [ ]:
# Eliminar eje 2
a = np.array([[[0], [1], [2]]])

print(f"a=\n{a}\n")
print(f"a.shape=\n{a.shape}\n")

b = np.squeeze(a, axis=2)

print(f"b=\n{b}\n")
print(f"b.shape=\n{b.shape}\n")

a=
[[[0]
  [1]
  [2]]]

a.shape=
(1, 3, 1)

b=
[[0 1 2]]

b.shape=
(1, 3)



# Ejercicios

## Dada la siguiente: matriz score_matrix Realizar las operaciones que se indican

```Python
# Definir un conjunto de datos de ventas (4 tiendas x 3 meses)
sales_data = np.array([
    [200000, 220000, 250000],  # Ventas de la tienda 1
    [150000, 180000, 210000],  # Ventas de la tienda 2
    [300000, 320000, 350000],  # Ventas de la tienda 3
    [400000, 420000, 430000]   # Ventas de la tienda 4
])

```

- ### Normalizar los datos de acuerdo al mes por medio de las matrices y vectores correspondientes:
   - ### dato\_normalizado =  (datos de ventas  - media de ventas) / desviación estandar de las ventas
   - ### Mostrar la media por mes
   - ### Mostrar la desviación estándar por mes
   - ### Mostrar los datos normalizados




In [3]:
sales_data = np.array([
    [200000, 220000, 250000],
    [150000, 180000, 210000],
    [300000, 320000, 350000],
    [400000, 420000, 430000] 
])
mu = np.mean(sales_data)
sigma = np.std(sales_data)
datos_normalizados = (sales_data - mu) / sigma
datos_normalizados

array([[-0.91458954, -0.7014813 , -0.38181893],
       [-1.44736014, -1.12769778, -0.80803542],
       [ 0.15095167,  0.36405991,  0.68372227],
       [ 1.21649288,  1.42960112,  1.53615524]])

## Ejercicios Broadcasting

# Ejercicio1. 

### Dada la siguientes definiciones para A y v, explicar ¿Qué pasos sigue NumPy para realizar esta suma y cómo afecta el resultado final?"

```Python
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

v = np.array([1, 0, -1])

B = A + v

```



<span style="color:lightgreen;">Ya que **A** tiene una dimensión mayor **(3,3)**, al vector **v** con forma **(3,)** se le agregan dimensiones para tener forma **(3,3)**. Los datos faltantes son "estirados" utilizando el vector **v** original, de manera que **v** se convierte en la matriz:</span>
```Python
[[1, 0, -1]
[1, 0, -1]
[1, 0, -1]]
```
<span style="color:lightgreen;">Luego, la operacion se hace como si de una suma de matrices comun se tratara</span>


In [11]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

v = np.array([1, 0, -1])

B = A + v
B

array([[2, 2, 2],
       [5, 5, 5],
       [8, 8, 8]])

## Ejercicio2. 

### Dada la siguientes definiciones para A y v, explicar ¿Qué pasos sigue NumPy para realizar esta suma y cómo afecta el resultado final?"


```Python
import numpy as np

# Crear una matriz 3x3
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])


v = np.array([[1],
              [2],
              [3]])


B = A * v

print(B)

```

<span style="color:lightgreen;">Ya que **A** tiene una dimensión mayor **(3,3)**, al vector vertical **v** con forma **(1,3)** se le agregan dimensiones para tener forma **(3,3)** en el eje que faltan. Los datos faltantes son "estirados" utilizando el vector **v** original, de manera que **v** se convierte en la matriz:</span>
```Python
[[1, 1, 1]
[2, 2, 2]
[3, 3, 3]]
```
<span style="color:lightgreen;">Luego, la operacion se hace como si de un producto Hadamard se tratara</span>

In [10]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])


v = np.array([[1],
              [2],
              [3]])


B = A * v
B

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

## Ejercicio3. 

### Dada la siguientes definiciones para A y v, explicar ¿Qué pasos sigue NumPy para realizar esta suma y cómo afecta el resultado final?"

```Python
import numpy as np

# Crear una matriz 3x3
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Sumar un escalar a la matriz
c = 10
B = A + c

print(B)

```

<span style="color:lightgreen;">Se compara la dimension de **A** y **c**, ya que **A** es la más grande con forma **(3,3)** se busca igualar **c** en dimensiones, primero se convierte en vector con forma **(1,)** luego en forma **(1,3)** y se estiran los datos. Finalmente se incrementea la dimensión 1 a **(3,3)** y se estiran los datos. En este punto se hace una suma de matrices normal.</span>

In [9]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Sumar un escalar a la matriz
c = 10
B = A + c
B

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

## Ejercicio4. 

### Dada la siguientes definiciones para A y v, explicar ¿Qué pasos sigue NumPy para realizar esta suma y cómo afecta el resultado final?"

```Python
import numpy as np

# Crear un vector de longitud 3
v = np.array([1, 2, 3])

# Crear una matriz 2x3
A = np.array([[4, 5, 6],
              [7, 8, 9]])

# Multiplicar el vector por la matriz
B = v * A

print(B)
```

<span style="color:lightgreen;">Se comparan las formas de **A (2,3)** y **v (3,)**. Dado que **A** es más grande, se busca igualar **v** estirando sus elementos en el eje de las filas hasta llegar a una matriz de forma **(2,3)**. Luego el producto Hadamard se hace normalmente</span>


In [8]:
v = np.array([1, 2, 3])

# Crear una matriz 2x3
A = np.array([[4, 5, 6],
              [7, 8, 9]])

# Multiplicar el vector por la matriz
B = v * A
B

array([[ 4, 10, 18],
       [ 7, 16, 27]])

## Ejercicio5. 

### Dada la siguientes definiciones para A y v, explicar ¿Qué pasos sigue NumPy para realizar esta suma y cómo afecta el resultado final?"

```Python
import numpy as np

# Crear una matriz 4x3
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])


mean1 = A.mean(axis=0)
print(mean1)

mean2 = A.mean(axis=0, keepdims=True)
print(mean2)


mean3 = A.mean(axis=1)
print(mean3)

mean4 = A.mean(axis=1, keepdims=True)
print(mean4)

```

<span style="color:lightgreen;">**mean1** calcula las medias de cada una de las columnas, el resultado es un vector **(3,)**</br>**mean2** hace lo mismo pero su resultado mantiene las dimensiones originales, por lo que es una matriz **(1,3)**</br>**mean3** calcula las medias pero de cada una de las filas, el resultado es un vector con forma **(4,)**</br>**mean4** hace lo mismo que **mean3** pero al conservar la misma dimensión que la matriz original, el resultado lo da con forma **(4,1)**</span>

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])


mean1 = A.mean(axis=0)
print(mean1)

mean2 = A.mean(axis=0, keepdims=True)
print(mean2)

mean3 = A.mean(axis=1)
print(mean3)

mean4 = A.mean(axis=1, keepdims=True)
print(mean4)

[5.5 6.5 7.5]
[[5.5 6.5 7.5]]
[ 2.  5.  8. 11.]
[[ 2.]
 [ 5.]
 [ 8.]
 [11.]]
(4, 1)


## Ejercicio6. 

## En este ejemplo de normalización de filas presentado, explica cómo se realiza el broadcasting para restar la media y dividir por la desviación estándar en cada fila de la matriz. Detalla cómo NumPy ajusta las dimensiones de los arreglos mean y std para permitir estas operaciones. Si es el caso, indicar cómo se expanden las dimensiones y replican los datos.

```Python
import numpy as np
# Crear una matriz 4x3
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

# Calcular la media 
mean = A.mean(axis=1, keepdims=True)

# Calcular la desviación estándar
std = A.std(axis=1, keepdims=True)

# Normalizar  (restar la media y dividir por la desviación estándar)
B = (A - mean) / std

print(B)

```

<span style="color:lightgreen;">Se compara la dimension de **A (4,3)** y **mean (4,1)**, ya que **A** es la más grande se busca igualar **mean** en dimensiones, primero se le agregan dimensiones hasta llegar a la forma **(3,4)** y el vector columna es duplicado en las demas columnas. En este punto se hace la resta de **A** con **mean**. Esta operación da como resultado una matriz **(4,3)** por lo que ahora se compara con **std**. El proceso que ocurre es el mismo que pasó con **A**, al ser la más grande se busca incrementar la dimensión de **std (4,1)** y al igual que con **mean**  se incrementa a **(4,3)** y se duplican los datos de las columnas. Finalmente se realiza la operación de división.</span>

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

# Calcular la media 
mean = A.mean(axis=1, keepdims=True)

# Calcular la desviación estándar
std = A.std(axis=1, keepdims=True)

# Normalizar  (restar la media y dividir por la desviación estándar)
B = (A - mean) / std

print(B)

[[0.81649658]
 [0.81649658]
 [0.81649658]
 [0.81649658]]
[[-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]]


# Ejercicio7

### En el ejemplo de cálculo de la distancia euclidiana, explica cómo se utiliza el broadcasting para restar el reference_point de todos los puntos en la matriz points. Además, describe cómo se aplica el broadcasting en la operación de elevación al cuadrado y la suma de los componentes para calcular la distancia.

### - Práctica: Adicionalmente, después de realizar la actividad anterior, modificar el programa para que el resultado mantenga la forma de la matriz original. 



### La ecuación de la distancia euclidiana entre dos puntos $ A = (x_1, y_1) $ y $ B = (x_2, y_2) $ en un espacio 2D es:


</br>

$
\Large d(A, B) = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}
$

</br>


```Python
import numpy as np

# Crear una matriz 5x2 donde cada fila es un punto (x, y) en 2D
points = np.array([[1, 2],
                   [3, 4],
                   [5, 6],
                   [7, 8],
                   [9, 10]])

# Definir un punto de referencia en 2D
reference_point = np.array([4, 5])

# Calcular la distancia euclidiana entre cada punto y el punto de referencia
distances = np.sqrt(np.sum((points - reference_point) ** 2, axis=1))

print(distances)

```

<span style="color:lightgreen;">Se compara la dimension de **points (5,2)** y **reference_point (2,)**, ya que **points** es la más grande se busca igualar **reference_point** en dimensiones, primero se le agrega una dimensión hasta llegar a la forma **(1,2)**. La matriz ahora se incrementa en dimensión una vez más con forma **(5,2)** y se duplican las filas. En este punto se hace la resta de **points** con **reference_point**. Al resultado con forma **(5,2)** se compara con el escalar 2. En este caso el escalar pasa a ser primero un vector **(1,)** y luego un vector **(1,2)** duplicando el dato; ahora pasa a la forma **(5,2)** y se duplican las filas. La operación se hace normalmente.</span>

In [35]:
points = np.array([[1, 2],
                   [3, 4],
                   [5, 6],
                   [7, 8],
                   [9, 10]])

# Definir un punto de referencia en 2D
reference_point = np.array([4, 5])

# Calcular la distancia euclidiana entre cada punto y el punto de referencia
distances = np.sqrt(np.sum((points - reference_point) ** 2, axis=1, keepdims=True))

print(distances)


[[4.24264069]
 [1.41421356]
 [1.41421356]
 [4.24264069]
 [7.07106781]]


# Representación de datos $X$, pesos $W$,  sesgos $B$ ($bias$) y neuronas en el contexto de redes neuronales

<img src="figs/fig-repr_red_neuronal.png" width="500">


## En las siguientes representaciones, 
 - ### $X$ : representa un conjunto de datos;  cada fila es un ejemplo y cada elemento (columna) representan una característica de los datos de entrenamiento, por ejemplo $x_{11}$

</br>

$$
\mathbf{X} = \begin{bmatrix}
x_{11} & x_{12} & \cdots & x_{1n} \\
x_{21} & x_{22} & \cdots & x_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
x_{m1} & x_{m2} & \cdots & x_{mn} \\
\end{bmatrix} \in \mathbb{R}^{m \times n}

$$

</br>

 - ### $W$ : representa un conjunto de neuronas; cada fila es una reurona y cada cada elemento (columna) representan un peso $w_{ik}$; neurona $i$; característica $k$

</br>

$$
\mathbf{W} = \begin{bmatrix}
w_{11} & w_{12} & \cdots & w_{1n} \\
w_{21} & w_{22} & \cdots & w_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
w_{m1} & w_{m2} & \cdots & w_{mn} \\
\end{bmatrix} \in \mathbb{R}^{m \times n}
$$

</br>

 - ### La neurona $N_1$ esta definida por la fila 1 de la matriz de pesos $W$: 
    $$ N_1 = \begin{bmatrix}w_{11} & w_{12} & \cdots & w_{1n}\end{bmatrix}$$

</br>

### La salida de cada neurona para la imagen del ejemplo se calcularía de la siguiente forma:


</br>

$$
    \mathbf{Y} =  \mathbf{X} \cdot\mathbf{W}^\top + \mathbf{B} = 
    \begin{bmatrix}
    x_1 & x_2 & x_3 & x_4 
    \end{bmatrix}
    \cdot
    \begin{bmatrix}
    w_{11} & w_{21} \\
    w_{12} & w_{22} \\
    w_{13} & w_{23} \\
    w_{14} & w_{24}
    \end{bmatrix}
    
    +
    \begin{bmatrix}
    b_1 & b_2 
    \end{bmatrix}

$$

</br>
</br>


$$
\mathbf{Y} = \mathbf{X} \cdot \mathbf{W}^\top + \mathbf{B} = 
\begin{bmatrix}
y_1 & y_2
\end{bmatrix}
= 
\begin{bmatrix}
(x_1 w_{11} + x_2 w_{12} + x_3 w_{13} + x_4 w_{14}) + b_1 & (x_1 w_{21} + x_2 w_{22} + x_3 w_{23} + x_4 w_{24}) + b_2
\end{bmatrix}
$$

</br>
</br>

$$

\mathbf{y_1}  =  (x_1 w_{11} + x_2 w_{12} + x_3 w_{13} + x_4 w_{14}) + b_1

$$

$$

\mathbf{y_2}  =  (x_1 w_{21} + x_2 w_{22} + x_3 w_{23} + x_4 w_{24}) + b_2

$$



# Ejercicio

## Para los siguientes datos, calcular la operación de cada neurona.
## Ejercicio1: 
- ### Hacer el cálculo para una capa de una red neuronal con el siguiente ejemplo de entrenamiento que contiene 10 características
- ### Definir la matriz de neuronas-pesos $W$ con 2 neuronas, inicializarla de forma aleatoria
- ### Definir el vector de sesgos $B$ inicializarlo de manera aleatoria

$$ 
\mathbf{X} = \begin{bmatrix}
1.2 & 0.5 & -0.8 & 2.1 & -1.5 & 0.3 & 1.8 & -0.2 & 0.9 & 1.1 \\
\end{bmatrix} \in \mathbb{R}^{1 \times 10}
$$

</br>
</br>
</br>

## Ejercicio2: 
- ### Hacer el cálculo para una capa de una red neuronal con el siguiente conjunto  de entrenamiento (3 ejemplos) que contiene 5 características
- ### Definir la matriz de neuronas-pesos $W$ con 2 neuronas, inicializarla de forma aleatoria
- ### Definir el vector de sesgos $B$ inicializarlo de manera aleatoria


$$ 
\mathbf{X} = \begin{bmatrix}
1.2 & 0.5 & -0.8 & 2.1 & -1.5  \\
0.8 & 1.2 & -0.3 & 1.5 & -0.8  \\
-0.5 & 1.8 & 0.2 & 0.9 & -1.2  \\
\end{bmatrix} \in \mathbb{R}^{3 \times 5}
$$


In [ ]:
X = np.array([1.2, 0.5, -0.8, 2.1, -1.5, 0.3, 1.8, -0.2, 0.9, 1.1])
W = np.random.rand(2,10)
B = np.random.rand(2)

print(f'X =\n{X}\nW =\n{W}\nB =\n{B}\n\nX(W^T) + B = {(X@W.T) + B}')


X =
[ 1.2  0.5 -0.8  2.1 -1.5  0.3  1.8 -0.2  0.9  1.1]
W =
[[0.80395328 0.33881425 0.37207637 0.63494682 0.04450071 0.43537048
  0.44717424 0.8962045  0.84572727 0.60182573]
 [0.80327662 0.22998242 0.44773362 0.48986366 0.13825427 0.97506632
  0.87919152 0.03653238 0.50986106 0.96455705]]
B =
[0.08477496 0.55583302]

X(W^T) + B = [4.36734889 5.48554742]


In [51]:
X = np.array([
    [1.2,  0.5, -0.8,  2.1, -1.5,  0.3,  1.8, -0.2,  0.9,  1.1],
    [0.8,  1.2, -0.3,  1.5, -0.8,  0.6,  2.1,  0.1,  1.2,  0.7],
    [-0.5, 1.8,  0.2,  0.9, -1.2,  1.1,  0.4, -0.3,  0.8,  1.5]
])
W = np.random.rand(2,10)
B = np.random.rand(2)

print(f'X =\n{X}\nW =\n{W}\nB =\n{B}\n\nX(W^T) + B = {(X@W.T) + B}')


X =
[[ 1.2  0.5 -0.8  2.1 -1.5  0.3  1.8 -0.2  0.9  1.1]
 [ 0.8  1.2 -0.3  1.5 -0.8  0.6  2.1  0.1  1.2  0.7]
 [-0.5  1.8  0.2  0.9 -1.2  1.1  0.4 -0.3  0.8  1.5]]
W =
[[0.61828576 0.81270378 0.33553189 0.67255556 0.83223356 0.89767342
  0.0811348  0.97206882 0.92489538 0.44042254]
 [0.13038883 0.26483378 0.09514136 0.34258216 0.0774024  0.99294112
  0.39995743 0.94818061 0.25106671 0.29666139]]
B =
[0.41328701 0.0913158 ]

X(W^T) + B = [[2.99497419 2.28786228]
 [4.34991134 2.97627267]
 [3.3695612  2.35090099]]
