In [5]:
import numpy as np

In [ ]:
class McCullochPittsNeuron:
    def __init__(self, threshold):
        """
        Inicializa la neurona con un umbral.
        :param threshold: Umbral para la función de activación
        """
        self.threshold = threshold

    def activate(self, inputs):
        """
        Calcula la salida de la neurona basada en las entradas.
        :param inputs: Lista o array de entradas (0 o 1)
        :return: Salida de la neurona (0 o 1)
        """
        # Calcula la suma de las entradas
        print(inputs)
        weighted_sum = inputs.sum() # suma todos los elementos
        
        # Aplica la función de activación (umbral)
        activacion = 0 
        if weighted_sum >= self.threshold: 
            activacion = 1
        return activacion

# Configura el umbral para la función AND

threshold = 2  # Umbral para que la suma sea al menos 2 para producir salida 1

# Crea la neurona
neuron = McCullochPittsNeuron(threshold)

# Prueba la neurona con todas las combinaciones de entradas para la función AND
inputs = np.array([c
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

# Imprime las salidas para cada combinación de entradas
for inp in inputs:
    output = neuron.activate(inp)
    print(f"Entrada: {inp}, Salida: {output}")

[0 0]
Entrada: [0 0], Salida: 0
[0 1]
Entrada: [0 1], Salida: 0
[1 0]
Entrada: [1 0], Salida: 0
[1 1]
Entrada: [1 1], Salida: 1


## Ejercicio1: 

### Diseñar e implementar en una clase una unidad McCulloch–Pitts capaz de reconocer la función AND y OR para 3 variables.

In [4]:
class NeuronaTripleAnd:
    def __init__(self):
        self.threshold = 3 

    def activate(self, inputs):
        weighted_sum = inputs.sum()
        activacion = 0 
        if weighted_sum >= self.threshold: 
            activacion = 1
        return activacion

class NeuronaTripleOr:
    def __init__(self):
        self.threshold = 1 

    def activate(self, inputs):
        weighted_sum = inputs.sum()
        activacion = 0 
        if weighted_sum >= self.threshold: 
            activacion = 1
        return activacion

neuronaOr = NeuronaTripleOr()
neuronaAnd = NeuronaTripleAnd()

inputs = np.array([
    [0, 0, 0],
    [0, 0, 1],
    [0, 1, 0],
    [0, 1, 1],
    [1, 0, 0],
    [1, 0, 1],
    [1, 1, 0],
    [1, 1, 1]
])

for inp in inputs:
    output = neuronaAnd.activate(inp)
    print(f"And {inp} = {output}")
    
for inp in inputs:
    output = neuronaOr.activate(inp)
    print(f"Or {inp} = {output}")

And [0 0 0] = 0
And [0 0 1] = 0
And [0 1 0] = 0
And [0 1 1] = 0
And [1 0 0] = 0
And [1 0 1] = 0
And [1 1 0] = 0
And [1 1 1] = 1
Or [0 0 0] = 0
Or [0 0 1] = 1
Or [0 1 0] = 1
Or [0 1 1] = 1
Or [1 0 0] = 1
Or [1 0 1] = 1
Or [1 1 0] = 1
Or [1 1 1] = 1


## Ejercicio 2: 

### Diseñar e implementar una unidad McCulloch–Pitts capaz de reconocer la letra "T" digitalizada en una matriz de 10 × 10 píxeles. Los píxeles oscuros deben codificarse como unos y los píxeles blancos como ceros.

In [23]:
class NeuronaT:
    def __init__(self):
        self.threshold = 36
        self.weights = np.array([
            [1]*10,
            [1]*10,
            [-1]*4+[1]*2+[-1]*4,
            [-1]*4+[1]*2+[-1]*4,
            [-1]*4+[1]*2+[-1]*4,
            [-1]*4+[1]*2+[-1]*4,
            [-1]*4+[1]*2+[-1]*4,
            [-1]*4+[1]*2+[-1]*4,
            [-1]*4+[1]*2+[-1]*4,
            [-1]*4+[1]*2+[-1]*4            
        ])

    def activate(self, inputs):

        weighted_sum = (inputs * self.weights).sum()
        activacion = 0 
        if weighted_sum >= self.threshold: 
            activacion = 1
        return activacion
    
T = np.array([
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
[0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 1, 0, 0, 0, 0]
])

neuronaT = NeuronaT()
print(f'Input:\n{T}\nOutput:\t{neuronaT.activate(T)}')


Input:
[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]]
Output:	1
